//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginDevExpress.LoginWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginWebService.ILogin")]
    public interface ILogin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/GetUsuarioData", ReplyAction="http://tempuri.org/ILogin/GetUsuarioDataResponse")]
        DatosLibrary.Usuario_ GetUsuarioData(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/GetUsuarioData", ReplyAction="http://tempuri.org/ILogin/GetUsuarioDataResponse")]
        System.Threading.Tasks.Task<DatosLibrary.Usuario_> GetUsuarioDataAsync(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/UsuarioLogin", ReplyAction="http://tempuri.org/ILogin/UsuarioLoginResponse")]
        string UsuarioLogin(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/UsuarioLogin", ReplyAction="http://tempuri.org/ILogin/UsuarioLoginResponse")]
        System.Threading.Tasks.Task<string> UsuarioLoginAsync(string usuario, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginChannel : LoginDevExpress.LoginWebService.ILogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginClient : System.ServiceModel.ClientBase<LoginDevExpress.LoginWebService.ILogin>, LoginDevExpress.LoginWebService.ILogin {
        
        public LoginClient() {
        }
        
        public LoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DatosLibrary.Usuario_ GetUsuarioData(string usuario, string password) {
            return base.Channel.GetUsuarioData(usuario, password);
        }
        
        public System.Threading.Tasks.Task<DatosLibrary.Usuario_> GetUsuarioDataAsync(string usuario, string password) {
            return base.Channel.GetUsuarioDataAsync(usuario, password);
        }
        
        public string UsuarioLogin(string usuario, string password) {
            return base.Channel.UsuarioLogin(usuario, password);
        }
        
        public System.Threading.Tasks.Task<string> UsuarioLoginAsync(string usuario, string password) {
            return base.Channel.UsuarioLoginAsync(usuario, password);
        }
    }
}
